apiVersion: cloud-build-notifiers/v1
kind: BigQueryNotifier
metadata:
  name: example-bigquery-notifier
spec:
  notification:
    filter: build.build_trigger_id == "cc97f48d-8e81-45a9-b80e-a74b3de81e5b"
    delivery:
      table: projects/aricz-notifiers-demo/datasets/notifiers_dataset/tables/trigger_table

