apiVersion: cloud-build-notifiers/v1
kind: BigQueryNotifier
metadata:
  name: example-bigquery-notifier
spec:
  notification:
    filter: build.build_trigger_id == "example_id"
    delivery:
      table: projects/project_name/datasets/example_dataset/tables/example_table

